### ISSUE TITLE
Use mdx instead of react-markdown?

### ISSUE THREAD

**Issue by Noviny** [Thinkmill/changelogs-xyz#1]
Found https://github.com/mdx-js/mdx/tree/master/packages/remark-mdx-remove-exports
and https://github.com/mdx-js/mdx/tree/master/packages/remark-mdx-remove-imports

which allows us to safely use mdx to render stuff. mdx gives really nice hooks for code styling etc, and I just generally like its API so considering switching. Any thoughts?

**Comment by mitchellhamilton** [comment]
Doesn't react-markdown let you replace elements too?

And those things wouldn't fix it since you could still do this:

```jsx
<div>{console.log('look, i can do whatever i want')}</div>
```

**Comment by Noviny** [comment]
Tru that - closing this in favour of more generic "let's style things" option
