### ISSUE TITLE
Understand release titles

### ISSUE THREAD

**Issue by jossmac** [Thinkmill/changelogs-xyz#21]
Looks like "react-virtualized" use `h5` for their titles:

![image](https://user-images.githubusercontent.com/2730833/76080074-40180480-5ffa-11ea-9a6a-f1fce991fb6f.png)

EDIT: they use `h2` for major, `h3` for minor, and `h5` for patch

**Comment by mitchellhamilton** [comment]
I'll probably take this because, as part of #24, I'll be looking at the AST so we can get the releases titles from that
