### ISSUE TITLE
Improve perf

### ISSUE THREAD

**Issue by Noviny** [Thinkmill/changelogs-xyz#24]
Currently loading the markdown is painfully slow after being fetched. This kind of kills any joy in using the site. We should fix this. Open to ideas.

**Comment by mitchellhamilton** [comment]
I might pick this up - doing perf things is fun and in this case it's Actually Good and not premature/over optimisation

**Comment by Noviny** [comment]
The perf issue is effectively 'if you have a really big markdown file, parsing takes a while'
I doubt there's going to be a clean answer to that still just using react-markdown.

Vague idea: batching this markdown fetching, so critical markdown chunks are parsed first (may clash with how Joss has done the side nav as it relies on there being one document)

Something else?

**Comment by mitchellhamilton** [comment]
I think the first thing would be parsing the markdown once if people use the range selector so that the range selector actually feels usable with large files

**Comment by Noviny** [comment]
We were thinking of making the range selector on enter not constantly filtering.

The biggest bottleneck IMO is that the loading spinner goes away, but nothing renders for maybe a second on large changelogs. If we could keep the spinner till markdown parse finished that would be good, or slight list virtualisation where we stagger adding markdown to the dom so top bits get added first, or detect that md parsing is still occurring and so keep the spinner and hide the `react-markdown` component.
