### ISSUE TITLE
Add package search

### ISSUE THREAD

**Issue by mitchellhamilton** [Thinkmill/changelogs-xyz#5]

**Comment by Noviny** [comment]
Real quick: do you mean predictive package search (hard) or, if no changelog is loaded, type in a full package name, hit enter, and how you get lucky (easy)?

**Comment by mitchellhamilton** [comment]
> predictive package search (hard)

It's not hard - https://api-docs.npms.io/#api-Search-ExecuteSearchQuery

**Comment by Noviny** [comment]
Hurrah for existing APIs!
